### ISSUE TITLE
webpack dev server hangs

### ISSUE THREAD

**Issue by Birowsky** [numical/style-ext-html-webpack-plugin#10]
Running the webpack-dev-server hangs.

This is the last thing I see in the console:

> [BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "100KB".

This is not a new message, i'm just noting the last thing i see.

My webpack version is 2.1.0-beta.25

I really wish i had any other info, but that's all i got. I'll make sure to answer any related questions you might have.

This is in my config:

```
{
  test: /critical.scss/,
  loader: ExtractTextPlugin.extract({
    fallbackLoader: 'style',
    loader: 'css!postcss!sass'
  })
}
```

**Comment by numical** [comment]
Have you worked through the step outlined in the [Debugging section of README.md](https://github.com/numical/style-ext-html-webpack-plugin#debugging)?

**Comment by Birowsky** [comment]
Of course not :} I'll get back to ya

**Comment by Birowsky** [comment]
It was caused by the ordering of the plugins. Not knowing that the plugin order matters, I added your plugin at the first place.

**Comment by numical** [comment]
Thanks for letting me know.
And - sorry - the plugin ordering was something I meant to mention in the README.md.
I will get that updated.

**Comment by Birowsky** [comment]
No problemo. Thanx for the great tool.
