### ISSUE TITLE
Add docs about inject option as necessary

### ISSUE THREAD

**Issue by rastasheep** [numical/style-ext-html-webpack-plugin#15]
This plugin doesn't work in cases when `inject` option of HTML Webpack Plugin is not on.

Modified head contents will not be added to resulting html without inject option, related code https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L287.

**Comment by numical** [comment]
That's true.
What are you after?
a) clearer documentation (sorry if you wasted time)
b) for this plugin to work even if `inject` is `false`?

**Comment by rastasheep** [comment]
No worries, it was interesting journey :)

I guess as first step docs should be fine.
Generally it would be awesome that plugin works even if `inject` is false. Probably it would be nice (if it's possible) in that case to plugin provide some variable with contents of style tag.

So if inject is false, everything is on you, you must provide template which manages behaviour where and what is  added to the template, and if inject is true, plugin magically injects everything for you, even inline styles.

Btw my workaround was to do `require` css file from ejs template, like [this example](https://github.com/webpack-contrib/html-loader#interpolation), but i've need to chage `${}` into `<%= %>` for ejs to work.

**Comment by numical** [comment]
Actually, now that I think about, it _ought_ to be possible to run this plugin even if `inject` is false. 
@jantimon has provided [a pretty decent set of hooks](https://github.com/jantimon/html-webpack-plugin#events) ('pretty decent' - British English equivalent to American English's 'awesome') into html-webpack-plugin's lifecycle.
Let me take a look - woud you be willing to try out any beta on your use case?
In the meantime I'll update the README so no-one else wastes the time you did (again, sorry).

**Comment by rastasheep** [comment]
Yeah ofc, no worries it's part of the learning process (and our business) :)

Currently i'm not sure that i would go that way in production, but yeah i'm ready to help.
That 'require' path looks maybe better in my case because i need some combination of inline and external scripts, so having one css file for external and one for inline looks ok for now.

**Comment by numical** [comment]
Okey dokey - release v3.2.0 no longer requires a truthy `inject` value, and also allows [positioning of style elements](https://github.com/numical/style-ext-html-webpack-plugin#use-case-specifying-position-of-style-element).  Let me now what you think, if you have any issues etc.

**Comment by rastasheep** [comment]
Awesome, thnx for quick solution. I'll check it out later today, on first sight it seems as very nice solution.

**Comment by sidonaldson** [comment]
@numical added into current build and it works just fine. Now injecting my priority.css into the head. Thanks!
