### ISSUE TITLE
Move <link> tags to the bottom of the paga (end of body)

### ISSUE THREAD

**Issue by thomaspink** [numical/style-ext-html-webpack-plugin#16]
**Original Text:**
As described in the documentation, css included with ExtractTextPlugin will be placed into the head tag:

If you have any CSS assets in webpack's output (for example, CSS extracted with the ExtractTextPlugin) then these will be included with tags in the HTML head.
Is there a way to move this tag to the body (end)?

Usecase:
I have two css files. The first one will be inlined in the head (using the StyleExtHtmlWebpackPlugin). The second one should be at the end of the body.

Original Issue: https://github.com/jantimon/html-webpack-plugin/issues/605

**Comment by numical** [comment]
@jantimon - further to [your request for a chat](https://github.com/jantimon/html-webpack-plugin/issues/605#issuecomment-282718168).  How about some time Wed 1st March?  I'm available most work hours?  I think you have my Skype..

**Comment by larvanitis** [comment]
Interested in that, too. My use case is an inlined app loader, which should be displayed asap. Right now the big css bundle delays the loader rendering.

**Comment by numical** [comment]
@larvanitis : does [this use case](https://github.com/numical/style-ext-html-webpack-plugin#use-case-internalize-critical-css-with-all-other-css-in-an-external-file) not satisfy your requirements?

**Comment by numical** [comment]
@thomaspink : can I clarify: do you want one <link> tag at the bottom of <body> and one <style> tag in <head>? If so I think, this plugin's config could get a lot ore complicated...

**Comment by thomaspink** [comment]
@numical  yeah, a style tag for "above the fold" in the head and a link with all the other styling in the bottom. i think a use case like this is very common on websites (not apps). 


**example production config:**
```js
const internalCSS = new ExtractTextPlugin('critical.css');
const externalCSS = new ExtractTextPlugin('main.css');

...

rules: [
      {
        test: /critical.scss$/,
        exclude: helpers.root('src', 'client', 'app'),
        use: internalCSS.extract({
          use: ['raw-loader', 'sass-loader']
        })
      }, {
        test: /main.scss$/,
        exclude: helpers.root('src', 'client', 'app'),
        use: externalCSS.extract({
          use: ['raw-loader', 'sass-loader']
        })
      }
    ]

...

plugins: [
  new HtmlWebpackExcludeAssetsPlugin(),

  internalCSS,
  externalCSS,
  new StyleExtHtmlWebpackPlugin('critical.css'),

  new HtmlWebpackPlugin({
      template: helpers.root('src', 'server', 'views', 'layouts', 'base.njk'),
      filename: helpers.root('dist', 'views', 'layouts', 'base.njk'),
      inject: 'body',
      excludeAssets: [/critical.*.js/, /main.*.js/]
    })
```

thanks for the help

**Comment by larvanitis** [comment]
@numical No, that use case does not work for me as I want to move the `link`ed stylesheet to the end of body

@thomaspink Is your _example production config_ a working one or the way it should work if implemented?

**Comment by larvanitis** [comment]
OK, I solved my problem by manually injecting the files in my template (`inject: false`) like this

```html
...

<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
<% } %>

<% for (var css in htmlWebpackPlugin.files.css) { %>
<link rel="stylesheet" property="stylesheet" href="<%= htmlWebpackPlugin.files.css[css] %>">
<% } %>
</body>
</html>
```

**Comment by thomaspink** [comment]
@larvanitis this example puts both, the above the fold css inline styles and the main css bundle in the head. the main should be in the bottom of the body

**Comment by thomaspink** [comment]
@numical @jantimon 
hey guys, is there an update on this one?

**Comment by numical** [comment]
Hi @thomaspink - sorry for the lack of visible progress this past fortnight.
I did chat with @jantimon about this, suggesting a couple of approaches that required changes to html-webpack-plugin.  He is not convinced of their need.
This leaves an approach where this plugin using some clever RegEx'ing to move the `<link>`'s around.
It's ugly and not core to this plugin's mission of inlining styles.  I may get to it - but not soon.  
Sorry for the delay in getting you this probably unsatisfactory answer.
PS : PR's welcome though!

**Comment by thomaspink** [comment]
Hi @numical thanks for the update.
I am sorry to hear this, as we switching a lot of projects from browserify to webpack and splitting the css into two parts (one inlined in the head for above the fold styles, and one linked in the bottom of the page for the rest) is googles recommended way to achieve good pagespeed ratings. :(

Maybe you can quickly sketch out the different approaches you guys discussed, so the community can maybe come up with solutions/PRs.

**Comment by Peiren** [comment]
@larvanitis 
Your solution is so GREAT

**Comment by numical** [comment]
Closing this issue as the functionality would require a almost complete rewrite to work around HtmlWebpackPlugin API (see my previous comment).
