### ISSUE TITLE
Combining with usual css loaders

### ISSUE THREAD

**Issue by jantimon** [numical/style-ext-html-webpack-plugin#2]
This plugin is awesome for inline the critical css.
It would be cool if you could show how non critical css and critical css can be go along in the readme.

E.g.

```js
module: {
  loaders: [
    { test: /\.critical\.css$/, loader: 'style-loader!css-loader' }
    { test: /^(?!.*\.critical).*\.css$/, loader: StyleExtHtmlWebpackPlugin.inline() }
  ]           
},
plugins: [
  new HtmlWebpackPlugin(),
  new StyleExtHtmlWebpackPlugin()
]  
```

This would allow critical css from `head.critical.css` to be inlined but `fancy-button.css` to be loaded by the css loader.

What do you think?

**Comment by numical** [comment]
Jan,
Don't use it yet!  
I hoped to make it production-ready over the Easter weekend but kids got in the way.
Hopefully early next week I will have it ready (aka fully tested) - I'll publish version 1.0.0 on npm.
As for non-critical CSS - you are absolutely right.  Tests will include running alongside the normal CSS loader, as per your example above, and alongside ExtractTextWebpackPlugin for <link>'d CSS files.
PS: thanks for example above - my RegEx is awful.

**Comment by jantimon** [comment]
Oh my regexp is switched - sry..
cool looking forward to your 1.0.0 I'll add a link as example for using events

**Comment by numical** [comment]
Docs and tests added in v 0.3.0
