### ISSUE TITLE
cssRegExp help!

### ISSUE THREAD

**Issue by sidonaldson** [numical/style-ext-html-webpack-plugin#21]
Hello, love this plugin and I'm already using it in a large traffic production site.

I've just attempted to add hashes into all my filenames to easy redeployment however I can't get `cssRegExp` to work.

Previously I had
```
new StyleExtHtmlWebpackPlugin({
    position: 'head-bottom',
    file: language + '.priority.css',
})
```

now I'm trying this, where the filename is [language].[hash].priority.css
```
new StyleExtHtmlWebpackPlugin({
    position: 'head-bottom',
    cssRegExp: /priority.css$/
})
```
What i'm seeing is always the main app.css inline in the head, no matter what order I change the entry points.
Any help would be appreciated.

**Comment by numical** [comment]
Ah!  The cssRegExp has only just gone in.  I will take a look...

**Comment by sidonaldson** [comment]
Sure, glad to help. 

```
StyleExt constructor: {"enabled":true,"position":"head-bottom","minify":false}} +0ms
 http://localhost:8080/
webpack result is served from /
content is served from /Users/sidonaldson/www/fidelity-international
404s will fallback to /index.html
  StyleExt CSS file in compilation: 'en.d067c598f3a47c3aef4e.app.css' +14s
  StyleExt CSS in compilation: /***************************
  StyleExt *
  StyleExt * All CSS
  StyleExt * - load everything into the bottom of the page
  StyleExt *
  StyleExt ****************************/
  StyleExt {
**** deleted ****
  StyleExt }
  StyleExt  +0ms
  StyleExt added new <style> +11ms
  StyleExt emit: asset 'en.d067c598f3a47c3aef4e.app.css' deleted +1ms
```

**Comment by sidonaldson** [comment]
Could it be that the version on NPM is a minor behind? https://www.npmjs.com/package/style-ext-html-webpack-plugin

**Comment by numical** [comment]
Ummm - yes. I did not publish.  
Time to get some automation into my release procedure!  
Sorry for your wasted time.

**Comment by sidonaldson** [comment]
@numical no problem! I'm annoyed with myself I didn't check the version number first. Congratulations on great plugin.
