### ISSUE TITLE
Chunks not working when HtmlWebpackPlugin has excludeChunks

### ISSUE THREAD

**Issue by milewski** [numical/style-ext-html-webpack-plugin#24]
It's not working if i dont specify chunks: in the **HtmlWebpackPlugin** for example

```js

entry: {
    'chinese-entry': './Chinese.css',
    'english-entry': './English.css',
    'portuguese-entry': './Portuguese.css',

    // other chunks that i want to be included on every .html goes here

}

/// ....

new HtmlWebpackPlugin({
    filename: 'chinese/index.html',
    excludeChunks: ['english-entry', 'portuguese-entry']
}),
new StyleExtHtmlWebpackPlugin({
    file: 'chinese/style.css',
    chunks: ['chinese-entry']
})

```

Note that in the **HtmlWebpackPlugin** i have only specified excludeChunks which implies that every other chunks will be included... meaning **chinese-chunk** is one of them.. but it is not working like this...

like this works:

```js
new HtmlWebpackPlugin({
    filename: 'chinese/index.html',
    chunks: ['chinese-entry', 'another-entry', 'here-is-one-more', 'not-sure-how-many-will-be']
}),
new StyleExtHtmlWebpackPlugin({
    file: 'chinese/style.css',
    chunks: ['chinese-entry']
})
```

**Comment by Milewski** [comment]
And actually after analyzing the output i also spotted that i got the inline style as well as the link tag

```html
<link href="/css/english.css" rel="stylesheet">
<style>
html { box-sizing: border-box}
.......
</style>
```

**Comment by numical** [comment]
Hi, sorry for the delay at looking at this. Hopefully I will get around to it his week.

**Comment by mbenedettini** [comment]
Same issue here, I had to manually specify chunks in `HtmlWebpackPlugin ` config, although `<link>` has been correctly replaced by `<style>`, I've only got the latter.

**Comment by kgrigorian** [comment]
any updates on this?

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained. I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing. I simply do not have the time to keep up. Sorry.
Please keep an eye on the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
