### ISSUE TITLE
inherit the attr option for style-loader?

### ISSUE THREAD

**Issue by zicjin** [numical/style-ext-html-webpack-plugin#25]
This configuration can be in accordance with the amp.
https://www.ampproject.org/docs/get_started/create/basic_markup

```
      var styleLoader = {
        loader: 'style-loader',
        options: {
          attrs: {
            'amp-custom': ''
          }
        }
      }
```

**Comment by numical** [comment]
Suprceeded by [PR 26](https://github.com/numical/style-ext-html-webpack-plugin/pull/26)
