### ISSUE TITLE
More available positions

### ISSUE THREAD

**Issue by cdreve** [numical/style-ext-html-webpack-plugin#28]
Hi,

I am currently building a widget that will be added to an existing html page from another project. I am using this plugin to inline the css rules. Using the plugin adds the `<head>` tag to the generated code, around the `<style>`.

@numical Would it be ok with you to add `position: top` or `position: absolute-top` and `position: bottom` or `position: absolute-bottom` which would inject the style at the top or bottom of html block, not taking into consideration `<head>`, `<body>` or any other tags?

P.S. When I tried to add the style as part of the generated JS, it increased the size by about 30k.

**Comment by numical** [comment]
Closed without fix for same reasons as [issue 16](https://github.com/numical/style-ext-html-webpack-plugin/issues/16)
