### ISSUE TITLE
Support for using with webpack-config

### ISSUE THREAD

**Issue by avaly** [numical/style-ext-html-webpack-plugin#30]
Similar to https://github.com/numical/script-ext-html-webpack-plugin/issues/23

**Comment by numical** [comment]
Hi,
I don't follow.
I accepted your PR and merged after minor changes.
What's this issue about?

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained. I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing. I simply do not have the time to keep up. Sorry.
Please keep an eye on the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
