### ISSUE TITLE
How to make it work with  critical CSS generation

### ISSUE THREAD

**Issue by IskanderMustafin** [numical/style-ext-html-webpack-plugin#37]
Hi. 

I need to implement critical CSS support for my application. 

I'm using [html-critical-webpack-plugin](https://github.com/anthonygore/html-critical-webpack-plugin) to generate critical CSS file (out of the box inliner doesn't work properly with EJS templates, that's why I need to use `StyleExtHtmlWebpackPlugin` plugin for inlining)

But when I'm trying to inline critical CSS generated by above plugin I'm getting this error:

```
[3] Error: css should not be empty
[3]     at D:\...\...\node_modules\penthouse\lib\index.js:308:33
[3]     at next (native)
[3]     at step (D:\...\...\node_modules\penthouse\lib\index.js:45:191)
[3]     at D:\...\...\node_modules\penthouse\lib\index.js:45:437
[3]     at D:\...\...\node_modules\penthouse\lib\index.js:45:99
[3]     at Promise (D:\...\...\node_modules\penthouse\lib\index.js:325:20)
[3]     at module.exports (D:\...\...\node_modules\penthouse\lib\index.js:269:10)
[3]     at D:\...\...\node_modules\critical\lib\core.js:170:16```
```

This is piece of my `webpack.config`: 

```
          module: {

                rules: [

                    {
                        test: /\.css$/,
                        use: ExtractTextPlugin.extract({
                            fallback: "style-loader",
                            use: [
                                {
                                    loader: 'css-loader',
                                },
                                {
                                    loader: "postcss-loader",
                                    options: {
                                        plugins: () => [require("autoprefixer")]
                                    }
                                }
                            ]
                        }),
                    },
                ],

            plugins: [
                new HtmlWebpackPlugin({
                    inject: true,
                    chunks: ['business', 'mpaVendor', 'manifest'],
                    filename: `${EJS_TEMPLATES_BUILD_DIR}/business/business.ejs`,
                    template: `!!raw-loader!${EJS_TEMPLATES_SRC_DIR}/business/business.ejs`, // raw-loaderfor EJS templates
                    minify: {
                        removeComments: true,
                        collapseWhitespace: true,
                        conservativeCollapse: true
                    }
                }),

                new ExtractTextPlugin('css/[name].css'),

                new HtmlCriticalPlugin({
                    base: path.join(__dirname, '..', 'build'),
                    src: 'server/features/business/business.ejs',
                    dest: 'site/css/business.critical.css',
                    minify: false,
                    extract: true,
                    inline: false,
                    width: 1300,
                    height: 900
                }),
                /*new StyleExtHtmlWebpackPlugin(' /critical\.css$')
                */
                new StyleExtHtmlWebpackPlugin('css/business.critical.css')
            ]
        }
```

Without using `StyleExtHtmlWebpackPlugin` the `business.critical.css` file generates properly. But when I'm adding  `StyleExtHtmlWebpackPlugin` I'm getting above error. 

I understand that error message points to `critical` plugin, so most likely it is not bug on your side. **But still it works OK if I just comment out `StyleExtHtmlWebpackPlugin`.** 

**Can you please help me to understand  how I can change my webpack configuration to make both plugins work together?** 

Thanks. 

UPDATE:
After build fails, I still can see that `HtmlWebpackPlugin` generates file, but instead of HTML/EJS code it contains error message: 

```
StyleExtHtmlWebpackPluginError: StyleExtHtmlWebpackPlugin: could not find Extr  actTextWebpackPlugin's generated .css file; available files: [list_of_css_files]
```
And of course there no `business.critical.css` file in the list of CSS files (because it fails to be generated). 

Probably I need somehow to order plugin execution - i.e. I need somehow cause `StyleExtHtmlWebpackPlugin` to wait until `html-critical-webpack-plugin` finish generating critical file.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained. I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing. I simply do not have the time to keep up. Sorry.
Please keep an eye on the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
