### ISSUE TITLE
issues in webpack 4

### ISSUE THREAD

**Issue by lucaszhu2zgf** [numical/style-ext-html-webpack-plugin#42]
In my project, use:
`"style-ext-html-webpack-plugin": "^4.0.1"`
`"webpack": "^4.28.1"`
everything seems ok, but actually in the html file with inline style tag and also the origin link tag
![_20181227170758](https://user-images.githubusercontent.com/2087827/50473988-23e20600-09fa-11e9-8af7-e6bfe7b6574d.png)

`   plugins.push(layoutStyle);`
`    plugins.push(new StyleExtHtmlWebpackPlugin('styles/main.css'));`
`    plugins.push(buyerStyle);`
`    plugins.push(supplierStyle);`

**Comment by icl7126** [comment]
I have the same problem.
Is this related to a specified webpack version?

**Comment by Ry7n** [comment]
I had this problem with multiple entries; the solution was to have one instance of the plugin per entry:

```js
const entry = {};
const htmlPackPlugins = [];
const styleInlinePlugins = [];

pages.forEach((page) => {
  entry[page] = [`path/to/${page}.tsx`];
  const chunks = [page];
  htmlPackPlugins.push(
    new HtmlWebpackPlugin({ chunks, filename: `${page}.html` })
  );
  styleInlinePlugins.push(
    new StyleExtHtmlWebpackPlugin({ chunks })
  );
});
module.exports = {
  entry,
  plugins: [
    ...htmlPackPlugins,
    new ScriptExtHtmlWebpackPlugin({
      inline: new RegExp(`(?:${pages.join('|')})\\.\\w+\\.js`)
    }),
    new MiniCssExtractPlugin(),
    ...styleInlinePlugins,
  ]
};

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained. I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing. I simply do not have the time to keep up. Sorry.
Please keep an eye on the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
