### ISSUE TITLE
Errors in html-webpack-plugin 4.1.0 and higher

### ISSUE THREAD

**Issue by ind1go** [numical/style-ext-html-webpack-plugin#50]
I get the following error when using a site with no `output.publicPath`, with `html-webpack-plugin` 4.1.0 and higher.

```
ERROR in   Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

      - validators.js:125 validateString
        internal/validators.js:125:11

      - replaceTag.js:21 convertToPath
        [graphiql]/[style-ext-html-webpack-plugin]/lib/replaceTag.js:21:72

      - replaceTag.js:62 replaceLinkTagWithStyleTag
        [graphiql]/[style-ext-html-webpack-plugin]/lib/replaceTag.js:62:21

      - plugin.js:81 wire
        [graphiql]/[style-ext-html-webpack-plugin]/lib/plugin.js:81:13

      - plugin.js:106 wrappedFn
        [graphiql]/[style-ext-html-webpack-plugin]/lib/plugin.js:106:9


      - new Promise


      - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
        [graphiql]/[tapable]/lib/Hook.js:154:20

      - index.js:190 assetsPromise.then
        [graphiql]/[html-webpack-plugin]/index.js:190:87

      - next_tick.js:68 process._tickCallback
        internal/process/next_tick.js:68:7
```

The problem appears to be that `this.childCompilationOutputName` was removed from `html-webpack-plugin` in 4.1.0.

Potential workarounds:

 - Add an `output.publicPath` to take the code down a different path. (I don't want to do this, I need relative links)
 - Downgrade to `html-webpack-plugin@4.0.4`.

**Comment by jvalecillos** [comment]
I can confirm that I have the exact same bug.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained. I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing. I simply do not have the time to keep up. Sorry.
Please keep an eye on the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
