### ISSUE TITLE
How do I add a nonce to my `<style>` tags?

### ISSUE THREAD

**Issue by Ashwin117** [numical/style-ext-html-webpack-plugin#53]
I'm dealing with a CSP problem. I want to pass a nonce to the `<link>` and `<style>` tags. How do I do this? I'm able to use the sister lib ScriptExtHtmlWebpackPlugin to achieve this for my `<script>` files.
```
new ScriptExtHtmlWebpackPlugin({
      custom: {
        test: /\.(js|css)$/,
        attribute: "nonce",
        value: "127237127"
      }
    }),
```

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained. I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing. I simply do not have the time to keep up. Sorry.
Please keep an eye on the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
