### ISSUE TITLE
error with webpack v5

### ISSUE THREAD

**Issue by njzjz** [numical/style-ext-html-webpack-plugin#54]
``` 
179   [webpack-cli] Promise rejection: Error: chunk.files was changed from Array to Set (using Array method 'splice' is not possible)
180    [webpack-cli] Error: chunk.files was changed from Array to Set (using Array method 'splice' is not possible)
181        at Set.set.<computed> [as splice] (/home/runner/work/reacnetgenerator/reacnetgenerator/reacnetgenerator/static/webpack/node_modules/webpack/lib/util/deprecation.js:117:10)
182        at /home/runner/work/reacnetgenerator/reacnetgenerator/reacnetgenerator/static/webpack/node_modules/style-ext-html-webpack-plugin/lib/removeFile.js:10:19
183        at Set.forEach (<anonymous>)
184        at deleteFileFromCompilation (/home/runner/work/reacnetgenerator/reacnetgenerator/reacnetgenerator/static/webpack/node_modules/style-ext-html-webpack-plugin/lib/removeFile.js:7:22)
185        at Set.forEach (<anonymous>)
186        at StyleExtHtmlWebpackPlugin.emitCallback (/home/runner/work/reacnetgenerator/reacnetgenerator/reacnetgenerator/static/webpack/node_modules/style-ext-html-webpack-plugin/lib/plugin.js:134:26)
187        at _next0 (eval at create (/home/runner/work/reacnetgenerator/reacnetgenerator/reacnetgenerator/static/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
188        at eval (eval at create (/home/runner/work/reacnetgenerator/reacnetgenerator/reacnetgenerator/static/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
189        at /home/runner/work/reacnetgenerator/reacnetgenerator/reacnetgenerator/static/webpack/node_modules/html-webpack-plugin/index.js:319:11
190        at processTicksAndRejections (internal/process/task_queues.js:93:5)
191    Done in 16.85s.
```

**Comment by njzjz** [comment]
The errors comes from https://github.com/numical/style-ext-html-webpack-plugin/blob/b6dda6bac6f251ffefa9a373184b1f0bfd1e368b/lib/removeFile.js#L10

**Comment by adamchal** [comment]
I was able to fix it locally by replacing L8-11
https://github.com/numical/style-ext-html-webpack-plugin/blob/b6dda6bac6f251ffefa9a373184b1f0bfd1e368b/lib/removeFile.js#L8-L11
with this
```javascript
if (Array.isArray(chunk.files)) {
  const fileIndex = chunk.files.indexOf(filename);
  if (fileIndex > -1) {
    chunk.files.splice(fileIndex, 1);
  }
} else {
  chunk.files.delete(filename);
}
```
This should allow for backward compatibility with older versions of Webpack that use an Array for `chunk.files` as well as Webpack 5+ that uses a Set.

@numical happy to send pull request if you’re still maintaining this.

**Comment by numical** [comment]
@adamchal - be warned that I found further problems with Webpack 5 in my regression tests.  However if it works for your use case, excellent!
Please note the next comment.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained. I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing. I simply do not have the time to keep up. Sorry.
Please keep an eye on the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
