### ISSUE TITLE
Error when using UglifyJS

### ISSUE THREAD

**Issue by lukaszgolder** [numical/style-ext-html-webpack-plugin#6]
I have an issue, when trying to build production version of application with the plugin. In development everything works like a charm but when I try build it UglifyJS returns an error:

``` javascript
SyntaxError: Unexpected token: punc (,) [./~/regenerator-runtime/runtime.js:506,5]
```

My loader configuration looks like this:

``` javascript
{
  test: /reset\.scss$/,
  loader: StyleExtHtmlWebpackPlugin.inline( ['postcss-loader', 'sass-loader'])
}
```

I import my scss file in the index.js file:

``` javascript
import './assets/styles/reset.scss';
```

Thanks for any help

**Comment by numical** [comment]
Hiya,
A [quick search](https://duckduckgo.com/?q=uglify.js+Unexpected+token%3A+punc+(%2C)&ia=qa) for Uglify errors seems to indicate some errors with things not getting transpiled in production envs.
I'm not quite sure how the style-ext-html-webpack-plugin's functionality would affect this.
Can I confirm the production build does not display this error is the plugin is not used? (Sorry - basics first)

**Comment by lukaszgolder** [comment]
Thx for the quick reply, 
production build dosn`t produce that error without plugin. Maybe the reason it is producing it is that he encounter css inside js code.

I was able to remove that error by adding 2 entry points and excluding the one with:

```javascript
require('./assets/styles/reset.scss');
```
from uglyfing and adding to html

**Comment by numical** [comment]
Excellent!  I like people who fix their own problems :-)  
When I get some time I will try to reproduce the problem and try to make the plugin more robust.
Thanks for letting me know your fix.

**Comment by jackfranklin** [comment]
I'm getting this issue too! It's obviously something to do with the CSS not being pulled into an external file, and then Uglify is running into it before it gets inlined.

The error I'm seeing is:

```
SyntaxError: Unexpected token name «inlined», expected punc «,» [./src/app/bootstrap.js:385,12]
```

Removing this plugin fixes that. I'm not sure what I can do to help you but please let me know any info that is useful :)

**Comment by numical** [comment]
@jackfranklin - thanks for letting me know.
Could I have a copy of your `webpack.config` and `package.json`?  Obviously I'm only really interested in bits pertinent to this problem so strip out anything you don't want me seeing.

**Comment by numical** [comment]
Hiya - v3.x of [StyleExtWebpackPlugin](https://github.com/numical/style-ext-html-webpack-plugin) just released - it should deal with this issue.  Let me know if not...
